/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './speaker-list';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import9 from 'ionic-angular/navigation/nav-controller';
import * as import10 from '../../providers/conference-data';
import * as import11 from 'ionic-angular/config/config';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from 'ionic-angular/components/toolbar/toolbar';
import * as import15 from 'ionic-angular/components/navbar/navbar';
import * as import16 from 'ionic-angular/components/button/button';
import * as import17 from 'ionic-angular/components/menu/menu-toggle';
import * as import18 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import19 from '@angular/core/src/linker/query_list';
import * as import20 from 'ionic-angular/components/icon/icon';
import * as import21 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import22 from 'ionic-angular/components/content/content';
import * as import23 from '@angular/common/src/directives/ng_for';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from 'ionic-angular/navigation/view-controller';
import * as import26 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import29 from 'ionic-angular/components/menu/menu-controller';
import * as import30 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import32 from 'ionic-angular/util/keyboard';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from '@angular/core/src/linker/template_ref';
import * as import36 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import37 from 'ionic-angular/components/card/card';
import * as import38 from 'ionic-angular/components/item/item';
import * as import39 from 'ionic-angular/components/avatar/avatar';
import * as import40 from 'ionic-angular/components/list/list';
import * as import41 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import42 from 'ionic-angular/util/form';
import * as import43 from 'ionic-angular/gestures/gesture-controller';
import * as import44 from '@angular/core/src/security';
var renderType_SpeakerListPage_Host:import0.RenderComponentType = (null as any);
class _View_SpeakerListPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SpeakerListPage_0_4:import3.SpeakerListPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SpeakerListPage_Host0,renderType_SpeakerListPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-speaker-list',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SpeakerListPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SpeakerListPage_0_4 = new import3.SpeakerListPage(this.parentInjector.get(import8.ActionSheetController),this.parentInjector.get(import9.NavController),this.parentInjector.get(import10.ConferenceData),this.parentInjector.get(import11.Config));
    this._appEl_0.initComponent(this._SpeakerListPage_0_4,([] as any[]),compView_0);
    compView_0.create(this._SpeakerListPage_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SpeakerListPage) && (0 === requestNodeIndex))) { return this._SpeakerListPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SpeakerListPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SpeakerListPage_Host === (null as any))) { (renderType_SpeakerListPage_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SpeakerListPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SpeakerListPageNgFactory:import13.ComponentFactory<import3.SpeakerListPage> = new import13.ComponentFactory<import3.SpeakerListPage>('page-speaker-list',viewFactory_SpeakerListPage_Host0,import3.SpeakerListPage);
const styles_SpeakerListPage:any[] = ([] as any[]);
var renderType_SpeakerListPage:import0.RenderComponentType = (null as any);
class _View_SpeakerListPage0 extends import1.AppView<import3.SpeakerListPage> {
  _el_0:any;
  _Header_0_3:import14.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import15.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import16.Button;
  _MenuToggle_4_5:import17.MenuToggle;
  _ToolbarItem_4_6:import18.ToolbarItem;
  _query_Button_4_0:import19.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import20.Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ToolbarTitle_9_4:import21.ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Content_14_4:import22.Content;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _TemplateRef_16_5:any;
  _NgFor_16_6:import23.NgFor;
  _text_17:any;
  _text_18:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SpeakerListPage0,renderType_SpeakerListPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import14.Header(this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import25.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import26.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import15.Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import9.NavController,(null as any)),this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import28.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import16.Button('','',this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import17.MenuToggle(this.parentInjector.get(import29.MenuController),new import24.ElementRef(this._el_4),this.parentInjector.get(import25.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_4_6 = new import18.ToolbarItem(this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import14.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import19.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import20.Icon(this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import2.AppElement(9,2,this,this._el_9);
    var compView_9:any = import30.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import21.ToolbarTitle(this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import14.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Speakers',(null as any));
    compView_9.create(this._ToolbarTitle_9_4,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','outer-content speaker-list');
    this._appEl_14 = new import2.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import31.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import22.Content(this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import32.Keyboard),this.parentInjector.get(import33.NgZone),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import34.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_16 = new import2.AppElement(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import35.TemplateRef_(this._appEl_16,viewFactory_SpeakerListPage1);
    this._NgFor_16_6 = new import23.NgFor(this._appEl_16.vcRef,this._TemplateRef_16_5,this.parentInjector.get(import36.IterableDiffers),this.ref);
    this._text_17 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._appEl_16,
        this._text_17
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import16.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4; }
    if (((token === import17.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5; }
    if (((token === import18.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6; }
    if (((token === import21.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4; }
    if (((token === import15.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4; }
    if (((token === import14.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3; }
    if (((token === import35.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import23.NgFor) && (16 === requestNodeIndex))) { return this._NgFor_16_6; }
    if (((token === import22.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Content_14_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_4_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_6_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_14_4.ngOnInit(); }
    changes = (null as any);
    const currVal_8:any = this.context.speakers;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgFor_16_6.ngForOf = currVal_8;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_8,currVal_8);
      this._expr_8 = currVal_8;
    }
    if ((changes !== (null as any))) { this._NgFor_16_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_16_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4]);
        this._ToolbarItem_4_6._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._Content_14_4.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SpeakerListPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SpeakerListPage> {
  if ((renderType_SpeakerListPage === (null as any))) { (renderType_SpeakerListPage = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_SpeakerListPage,{})); }
  return new _View_SpeakerListPage0(viewUtils,parentInjector,declarationEl);
}
class _View_SpeakerListPage1 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import37.Card;
  _text_1:any;
  _el_2:any;
  _CardHeader_2_3:import37.CardHeader;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Item_4_4:import38.Item;
  _ItemContent_4_5:import38.ItemContent;
  _query_Label_4_0:import19.QueryList<any>;
  _query_Button_4_1:import19.QueryList<any>;
  _query_Icon_4_2:import19.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Avatar_6_3:import39.Avatar;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _Button_11_4:import16.Button;
  _text_12:any;
  _el_13:any;
  _Icon_13_3:import20.Icon;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _CardContent_18_3:import37.CardContent;
  _text_19:any;
  _el_20:any;
  _List_20_3:import40.List;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _TemplateRef_22_5:any;
  _NgFor_22_6:import23.NgFor;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _Item_24_4:import38.Item;
  _ItemContent_24_5:import38.ItemContent;
  _query_Label_24_0:import19.QueryList<any>;
  _query_Button_24_1:import19.QueryList<any>;
  _query_Icon_24_2:import19.QueryList<any>;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _Item_32_4:import38.Item;
  _ItemContent_32_5:import38.ItemContent;
  _query_Label_32_0:import19.QueryList<any>;
  _query_Button_32_1:import19.QueryList<any>;
  _query_Icon_32_2:import19.QueryList<any>;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _Button_34_4:import16.Button;
  _text_35:any;
  _el_36:any;
  _Icon_36_3:import20.Icon;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import2.AppElement;
  _Button_39_4:import16.Button;
  _text_40:any;
  _el_41:any;
  _Icon_41_3:import20.Icon;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SpeakerListPage1,renderType_SpeakerListPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','speaker');
    this._Card_0_3 = new import37.Card(this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card-header',(null as any));
    this._CardHeader_2_3 = new import37.CardHeader();
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','item item-block');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import41.viewFactory_Item0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Item_4_4 = new import38.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_4),this.renderer);
    this._ItemContent_4_5 = new import38.ItemContent();
    this._query_Label_4_0 = new import19.QueryList<any>();
    this._query_Button_4_1 = new import19.QueryList<any>();
    this._query_Icon_4_2 = new import19.QueryList<any>();
    this._appEl_4.initComponent(this._Item_4_4,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_6,'item-left','');
    this._Avatar_6_3 = new import39.Avatar();
    this._text_7 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'img',(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_10 = this.renderer.createText((null as any),'',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_11,'clear','');
    this.renderer.setElementAttribute(this._el_11,'icon-only','');
    this.renderer.setElementAttribute(this._el_11,'ion-button','');
    this.renderer.setElementAttribute(this._el_11,'item-right','');
    this._appEl_11 = new import2.AppElement(11,4,this,this._el_11);
    var compView_11:any = import28.viewFactory_Button0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Button_11_4 = new import16.Button((null as any),'',this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_11),this.renderer);
    this._appEl_11.initComponent(this._Button_11_4,([] as any[]),compView_11);
    this._text_12 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_13,'name','help-circle');
    this.renderer.setElementAttribute(this._el_13,'role','img');
    this._Icon_13_3 = new import20.Icon(this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_13),this.renderer);
    this._text_14 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_11.create(this._Button_11_4,[([] as any[]).concat([
        this._text_12,
        this._el_13,
        this._text_14
      ]
    )],(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_4_0.reset(([] as any[]));
    this._Item_4_4.contentLabel = this._query_Label_4_0.first;
    compView_4.create(this._Item_4_4,[
      ([] as any[]).concat([this._el_6]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_5,
        this._text_10,
        this._text_15
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_11])
    ]
    ,(null as any));
    this._text_16 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_0,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','outer-content');
    this._CardContent_18_3 = new import37.CardContent();
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-list',(null as any));
    this._List_20_3 = new import40.List(this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_20),this.renderer,this.parent.parentInjector.get(import43.GestureController));
    this._text_21 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._appEl_22 = new import2.AppElement(22,20,this,this._anchor_22);
    this._TemplateRef_22_5 = new import35.TemplateRef_(this._appEl_22,viewFactory_SpeakerListPage2);
    this._NgFor_22_6 = new import23.NgFor(this._appEl_22.vcRef,this._TemplateRef_22_5,this.parent.parentInjector.get(import36.IterableDiffers),this.parent.ref);
    this._text_23 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_20,'button',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','item item-block');
    this.renderer.setElementAttribute(this._el_24,'ion-item','');
    this._appEl_24 = new import2.AppElement(24,20,this,this._el_24);
    var compView_24:any = import41.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import38.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_24),this.renderer);
    this._ItemContent_24_5 = new import38.ItemContent();
    this._query_Label_24_0 = new import19.QueryList<any>();
    this._query_Button_24_1 = new import19.QueryList<any>();
    this._query_Icon_24_2 = new import19.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_24_0.reset(([] as any[]));
    this._Item_24_4.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_25,
        this._el_26,
        this._text_28
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_29 = this.renderer.createText(this._el_20,'\n      ',(null as any));
    this._text_30 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','item item-block');
    this._appEl_32 = new import2.AppElement(32,0,this,this._el_32);
    var compView_32:any = import41.viewFactory_Item0(this.viewUtils,this.injector(32),this._appEl_32);
    this._Item_32_4 = new import38.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_32),this.renderer);
    this._ItemContent_32_5 = new import38.ItemContent();
    this._query_Label_32_0 = new import19.QueryList<any>();
    this._query_Button_32_1 = new import19.QueryList<any>();
    this._query_Icon_32_2 = new import19.QueryList<any>();
    this._appEl_32.initComponent(this._Item_32_4,([] as any[]),compView_32);
    this._text_33 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_34,'clear','');
    this.renderer.setElementAttribute(this._el_34,'icon-left','');
    this.renderer.setElementAttribute(this._el_34,'ion-button','');
    this.renderer.setElementAttribute(this._el_34,'item-left','');
    this._appEl_34 = new import2.AppElement(34,32,this,this._el_34);
    var compView_34:any = import28.viewFactory_Button0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Button_34_4 = new import16.Button((null as any),'',this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_34),this.renderer);
    this._appEl_34.initComponent(this._Button_34_4,([] as any[]),compView_34);
    this._text_35 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_36,'name','logo-twitter');
    this.renderer.setElementAttribute(this._el_36,'role','img');
    this._Icon_36_3 = new import20.Icon(this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_36),this.renderer);
    this._text_37 = this.renderer.createText((null as any),'\n        Tweet\n      ',(null as any));
      compView_34.create(this._Button_34_4,[([] as any[]).concat([
        this._text_35,
        this._el_36,
        this._text_37
      ]
    )],(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_39,'clear','');
    this.renderer.setElementAttribute(this._el_39,'icon-left','');
    this.renderer.setElementAttribute(this._el_39,'ion-button','');
    this.renderer.setElementAttribute(this._el_39,'item-right','');
    this._appEl_39 = new import2.AppElement(39,32,this,this._el_39);
    var compView_39:any = import28.viewFactory_Button0(this.viewUtils,this.injector(39),this._appEl_39);
    this._Button_39_4 = new import16.Button((null as any),'',this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_39),this.renderer);
    this._appEl_39.initComponent(this._Button_39_4,([] as any[]),compView_39);
    this._text_40 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_41,'name','share');
    this.renderer.setElementAttribute(this._el_41,'role','img');
    this._Icon_41_3 = new import20.Icon(this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_41),this.renderer);
    this._text_42 = this.renderer.createText((null as any),'\n        Share\n      ',(null as any));
      compView_39.create(this._Button_39_4,[([] as any[]).concat([
        this._text_40,
        this._el_41,
        this._text_42
      ]
    )],(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_32_0.reset(([] as any[]));
    this._Item_32_4.contentLabel = this._query_Label_32_0.first;
    compView_32.create(this._Item_32_4,[
      ([] as any[]).concat([this._el_34]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_33,
        this._text_38,
        this._text_43
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_39])
    ]
    ,(null as any));
    this._text_44 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_24,'click',this.eventHandler(this._handle_click_24_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_34,'click',this.eventHandler(this._handle_click_34_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_39,'click',this.eventHandler(this._handle_click_39_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import39.Avatar) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Avatar_6_3; }
    if (((token === import20.Icon) && (13 === requestNodeIndex))) { return this._Icon_13_3; }
    if (((token === import16.Button) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Button_11_4; }
    if (((token === import38.Item) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Item_4_4; }
    if (((token === import38.ItemContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._ItemContent_4_5; }
    if (((token === import37.CardHeader) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._CardHeader_2_3; }
    if (((token === import35.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import23.NgFor) && (22 === requestNodeIndex))) { return this._NgFor_22_6; }
    if (((token === import38.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Item_24_4; }
    if (((token === import38.ItemContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ItemContent_24_5; }
    if (((token === import40.List) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._List_20_3; }
    if (((token === import37.CardContent) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._CardContent_18_3; }
    if (((token === import20.Icon) && (36 === requestNodeIndex))) { return this._Icon_36_3; }
    if (((token === import16.Button) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Button_34_4; }
    if (((token === import20.Icon) && (41 === requestNodeIndex))) { return this._Icon_41_3; }
    if (((token === import16.Button) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Button_39_4; }
    if (((token === import38.Item) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Item_32_4; }
    if (((token === import38.ItemContent) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._ItemContent_32_5; }
    if (((token === import37.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Card_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changed = false;
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Button_11_4.clear = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_11.componentView.markAsCheckOnce(); }
    const currVal_4:any = 'help-circle';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_13_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    changes = (null as any);
    const currVal_6:any = this.context.$implicit.sessions;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgFor_22_6.ngForOf = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._NgFor_22_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_22_6.ngDoCheck(); }
    changed = false;
    const currVal_10:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Button_34_4.clear = currVal_10;
      changed = true;
      this._expr_10 = currVal_10;
    }
    if (changed) { this._appEl_34.componentView.markAsCheckOnce(); }
    const currVal_11:any = 'logo-twitter';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Icon_36_3.name = currVal_11;
      this._expr_11 = currVal_11;
    }
    changed = false;
    const currVal_14:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._Button_39_4.clear = currVal_14;
      changed = true;
      this._expr_14 = currVal_14;
    }
    if (changed) { this._appEl_39.componentView.markAsCheckOnce(); }
    const currVal_15:any = 'share';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._Icon_41_3.name = currVal_15;
      this._expr_15 = currVal_15;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_1.dirty) {
        this._query_Button_4_1.reset([this._Button_11_4]);
        this._Item_4_4._buttons = this._query_Button_4_1;
        this._query_Button_4_1.notifyOnChanges();
      }
      if (this._query_Icon_4_2.dirty) {
        this._query_Icon_4_2.reset(([] as any[]));
        this._Item_4_4._icons = this._query_Icon_4_2;
        this._query_Icon_4_2.notifyOnChanges();
      }
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset(([] as any[]));
        this._Item_24_4._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset(([] as any[]));
        this._Item_24_4._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if (this._query_Button_32_1.dirty) {
        this._query_Button_32_1.reset([
          this._Button_34_4,
          this._Button_39_4
        ]
        );
        this._Item_32_4._buttons = this._query_Button_32_1;
        this._query_Button_32_1.notifyOnChanges();
      }
      if (this._query_Icon_32_2.dirty) {
        this._query_Icon_32_2.reset(([] as any[]));
        this._Item_32_4._icons = this._query_Icon_32_2;
        this._query_Icon_32_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_11_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_24_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_34_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_39_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_32_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this.context.$implicit.profilePic;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_8,'src',this.viewUtils.sanitizer.sanitize(import44.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'\n        ',this.context.$implicit.name,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_10,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_5:any = this._Icon_13_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_13,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = import4.interpolate(1,'About ',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_27,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_12:any = this._Icon_36_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_36,'hide',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_16:any = this._Icon_41_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_41,'hide',currVal_16);
      this._expr_16 = currVal_16;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_13_3.ngOnDestroy();
    this._Icon_36_3.ngOnDestroy();
    this._Icon_41_3.ngOnDestroy();
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openContact(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_24_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.goToSpeakerDetail(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.goToSpeakerTwitter(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_39_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openSpeakerShare(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_SpeakerListPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SpeakerListPage1(viewUtils,parentInjector,declarationEl);
}
class _View_SpeakerListPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import38.Item;
  _ItemContent_0_5:import38.ItemContent;
  _query_Label_0_0:import19.QueryList<any>;
  _query_Button_0_1:import19.QueryList<any>;
  _query_Icon_0_2:import19.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SpeakerListPage2,renderType_SpeakerListPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import41.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import38.Item(this.parent.parent.parentInjector.get(import42.Form),this.parent.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import38.ItemContent();
    this._query_Label_0_0 = new import19.QueryList<any>();
    this._query_Button_0_1 = new import19.QueryList<any>();
    this._query_Icon_0_2 = new import19.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import38.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Item_0_4; }
    if (((token === import38.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._ItemContent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.goToSessionDetail(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_SpeakerListPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SpeakerListPage2(viewUtils,parentInjector,declarationEl);
}