/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './schedule';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/components/alert/alert';
import * as import9 from 'ionic-angular/components/app/app';
import * as import10 from 'ionic-angular/components/modal/modal';
import * as import11 from 'ionic-angular/navigation/nav-controller';
import * as import12 from '../../providers/conference-data';
import * as import13 from '../../providers/user-data';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from 'ionic-angular/components/toolbar/toolbar';
import * as import18 from 'ionic-angular/components/navbar/navbar';
import * as import19 from 'ionic-angular/components/button/button';
import * as import20 from 'ionic-angular/components/menu/menu-toggle';
import * as import21 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import22 from 'ionic-angular/components/icon/icon';
import * as import23 from '@angular/forms/src/directives/ng_model';
import * as import24 from '@angular/forms/src/directives/ng_control_status';
import * as import25 from 'ionic-angular/components/segment/segment';
import * as import26 from 'ionic-angular/components/searchbar/searchbar';
import * as import27 from 'ionic-angular/components/content/content';
import * as import28 from 'ionic-angular/components/list/list';
import * as import29 from '@angular/common/src/directives/ng_for';
import * as import30 from 'ionic-angular/components/item/item';
import * as import31 from 'ionic-angular/components/list/list-header';
import * as import32 from '@angular/common/src/pipes/lowercase_pipe';
import * as import33 from 'ionic-angular/config/config';
import * as import34 from '@angular/core/src/linker/element_ref';
import * as import35 from 'ionic-angular/navigation/view-controller';
import * as import36 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import37 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import38 from 'ionic-angular/components/menu/menu-controller';
import * as import39 from '../../node_modules/ionic-angular/components/segment/segment.ngfactory';
import * as import40 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import41 from '../../node_modules/ionic-angular/components/searchbar/searchbar.ngfactory';
import * as import42 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import43 from 'ionic-angular/util/keyboard';
import * as import44 from '@angular/core/src/zone/ng_zone';
import * as import45 from 'ionic-angular/components/tabs/tabs';
import * as import46 from 'ionic-angular/gestures/gesture-controller';
import * as import47 from '@angular/core/src/linker/template_ref';
import * as import48 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import49 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import50 from 'ionic-angular/util/form';
import * as import51 from '@angular/forms/src/directives/ng_control';
import * as import52 from 'ionic-angular/components/label/label';
import * as import53 from 'ionic-angular/components/item/item-sliding';
import * as import54 from '@angular/common/src/directives/ng_if';
import * as import55 from '../../node_modules/ionic-angular/components/item/item-sliding.ngfactory';
var renderType_SchedulePage_Host:import0.RenderComponentType = (null as any);
class _View_SchedulePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SchedulePage_0_4:import3.SchedulePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SchedulePage_Host0,renderType_SchedulePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-schedule',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SchedulePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SchedulePage_0_4 = new import3.SchedulePage(this.parentInjector.get(import8.AlertController),this.parentInjector.get(import9.App),this.parentInjector.get(import10.ModalController),this.parentInjector.get(import11.NavController),this.parentInjector.get(import12.ConferenceData),this.parentInjector.get(import13.UserData));
    this._appEl_0.initComponent(this._SchedulePage_0_4,([] as any[]),compView_0);
    compView_0.create(this._SchedulePage_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SchedulePage) && (0 === requestNodeIndex))) { return this._SchedulePage_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._SchedulePage_0_4.ngAfterViewInit(); } }
  }
}
function viewFactory_SchedulePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SchedulePage_Host === (null as any))) { (renderType_SchedulePage_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SchedulePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SchedulePageNgFactory:import15.ComponentFactory<import3.SchedulePage> = new import15.ComponentFactory<import3.SchedulePage>('page-schedule',viewFactory_SchedulePage_Host0,import3.SchedulePage);
const styles_SchedulePage:any[] = ([] as any[]);
var renderType_SchedulePage:import0.RenderComponentType = (null as any);
class _View_SchedulePage0 extends import1.AppView<import3.SchedulePage> {
  _viewQuery_scheduleList_0:import16.QueryList<any>;
  _el_0:any;
  _Header_0_3:import17.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import18.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import19.Button;
  _MenuToggle_4_5:import20.MenuToggle;
  _ToolbarItem_4_6:import21.ToolbarItem;
  _query_Button_4_0:import16.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import22.Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _NgModel_9_3:import23.NgModel;
  _NgControl_9_4:any;
  _NgControlStatus_9_5:import24.NgControlStatus;
  _Segment_9_6:import25.Segment;
  _query_SegmentButton_9_0:import16.QueryList<any>;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _SegmentButton_11_4:import25.SegmentButton;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _SegmentButton_14_4:import25.SegmentButton;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _ToolbarItem_18_3:import21.ToolbarItem;
  _query_Button_18_0:import16.QueryList<any>;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _Button_20_4:import19.Button;
  _text_21:any;
  _el_22:any;
  _Icon_22_3:import22.Icon;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _Toolbar_27_4:import17.Toolbar;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _NgModel_29_4:import23.NgModel;
  _NgControl_29_5:any;
  _NgControlStatus_29_6:import24.NgControlStatus;
  _Searchbar_29_7:import26.Searchbar;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _Content_34_4:import27.Content;
  _text_35:any;
  _el_36:any;
  _List_36_3:import28.List;
  _text_37:any;
  _anchor_38:any;
  /*private*/ _appEl_38:import2.AppElement;
  _TemplateRef_38_5:any;
  _NgFor_38_6:import29.NgFor;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import2.AppElement;
  _Item_41_4:import30.Item;
  _ListHeader_41_5:import31.ListHeader;
  _query_Label_41_0:import16.QueryList<any>;
  _query_Button_41_1:import16.QueryList<any>;
  _query_Icon_41_2:import16.QueryList<any>;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  _pipe_lowercase_0:import32.LowerCasePipe;
  /*private*/ _expr_45:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SchedulePage0,renderType_SchedulePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_scheduleList_0 = new import16.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import17.Header(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import35.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'no-border-bottom','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import36.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Navbar(this.parentInjector.get(import9.App),this.parentInjector.get(import35.ViewController,(null as any)),this.parentInjector.get(import11.NavController,(null as any)),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import37.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import19.Button('','',this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import20.MenuToggle(this.parentInjector.get(import38.MenuController),new import34.ElementRef(this._el_4),this.parentInjector.get(import35.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_4_6 = new import21.ToolbarItem(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import17.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import16.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import22.Icon(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-segment',(null as any));
    this._NgModel_9_3 = new import23.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_9_4 = this._NgModel_9_3;
    this._NgControlStatus_9_5 = new import24.NgControlStatus(this._NgControl_9_4);
    this._Segment_9_6 = new import25.Segment(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_9),this.renderer,this._NgControl_9_4);
    this._query_SegmentButton_9_0 = new import16.QueryList<any>();
    this._text_10 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','segment-button');
    this.renderer.setElementAttribute(this._el_11,'role','button');
    this.renderer.setElementAttribute(this._el_11,'tappable','');
    this.renderer.setElementAttribute(this._el_11,'value','all');
    this._appEl_11 = new import2.AppElement(11,9,this,this._el_11);
    var compView_11:any = import39.viewFactory_SegmentButton0(this.viewUtils,this.injector(11),this._appEl_11);
    this._SegmentButton_11_4 = new import25.SegmentButton(this.renderer,new import34.ElementRef(this._el_11));
    this._appEl_11.initComponent(this._SegmentButton_11_4,([] as any[]),compView_11);
    this._text_12 = this.renderer.createText((null as any),'\n        All\n      ',(null as any));
    compView_11.create(this._SegmentButton_11_4,[([] as any[]).concat([this._text_12])],(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_9,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','segment-button');
    this.renderer.setElementAttribute(this._el_14,'role','button');
    this.renderer.setElementAttribute(this._el_14,'tappable','');
    this.renderer.setElementAttribute(this._el_14,'value','favorites');
    this._appEl_14 = new import2.AppElement(14,9,this,this._el_14);
    var compView_14:any = import39.viewFactory_SegmentButton0(this.viewUtils,this.injector(14),this._appEl_14);
    this._SegmentButton_14_4 = new import25.SegmentButton(this.renderer,new import34.ElementRef(this._el_14));
    this._appEl_14.initComponent(this._SegmentButton_14_4,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n        Favorites\n      ',(null as any));
    compView_14.create(this._SegmentButton_14_4,[([] as any[]).concat([this._text_15])],(null as any));
    this._text_16 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_18,'end','');
    this._ToolbarItem_18_3 = new import21.ToolbarItem(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import17.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_18_0 = new import16.QueryList<any>();
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'button',(null as any));
    this.renderer.setElementAttribute(this._el_20,'icon-only','');
    this.renderer.setElementAttribute(this._el_20,'ion-button','');
    this._appEl_20 = new import2.AppElement(20,18,this,this._el_20);
    var compView_20:any = import37.viewFactory_Button0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Button_20_4 = new import19.Button((null as any),'',this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_20),this.renderer);
    this._appEl_20.initComponent(this._Button_20_4,([] as any[]),compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_22,'ios','ios-options-outline');
    this.renderer.setElementAttribute(this._el_22,'md','md-options');
    this.renderer.setElementAttribute(this._el_22,'role','img');
    this._Icon_22_3 = new import22.Icon(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_22),this.renderer);
    this._text_23 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_20.create(this._Button_20_4,[([] as any[]).concat([
        this._text_21,
        this._el_22,
        this._text_23
      ]
    )],(null as any));
    this._text_24 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]).concat([this._el_18]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_17,
        this._text_25
      ]
      )
    ]
    ,(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_0,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','toolbar');
    this.renderer.setElementAttribute(this._el_27,'no-border-top','');
    this._appEl_27 = new import2.AppElement(27,0,this,this._el_27);
    var compView_27:any = import40.viewFactory_Toolbar0(this.viewUtils,this.injector(27),this._appEl_27);
    this._Toolbar_27_4 = new import17.Toolbar(this.parentInjector.get(import35.ViewController,(null as any)),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_27),this.renderer);
    this._appEl_27.initComponent(this._Toolbar_27_4,([] as any[]),compView_27);
    this._text_28 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'ion-searchbar',(null as any));
    this.renderer.setElementAttribute(this._el_29,'color','primary');
    this.renderer.setElementAttribute(this._el_29,'placeholder','Search');
    this._appEl_29 = new import2.AppElement(29,27,this,this._el_29);
    var compView_29:any = import41.viewFactory_Searchbar0(this.viewUtils,this.injector(29),this._appEl_29);
    this._NgModel_29_4 = new import23.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_29_5 = this._NgModel_29_4;
    this._NgControlStatus_29_6 = new import24.NgControlStatus(this._NgControl_29_5);
    this._Searchbar_29_7 = new import26.Searchbar(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_29),this.renderer,this._NgControl_29_5);
    this._appEl_29.initComponent(this._Searchbar_29_7,([] as any[]),compView_29);
    this._text_30 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_29.create(this._Searchbar_29_7,([] as any[]),(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_27.create(this._Toolbar_27_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_28,
        this._el_29,
        this._text_31
      ]
      )
    ]
    ,(null as any));
    this._text_32 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_33 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_34 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_34 = new import2.AppElement(34,(null as any),this,this._el_34);
    var compView_34:any = import42.viewFactory_Content0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Content_34_4 = new import27.Content(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_34),this.renderer,this.parentInjector.get(import9.App),this.parentInjector.get(import43.Keyboard),this.parentInjector.get(import44.NgZone),this.parentInjector.get(import35.ViewController,(null as any)),this.parentInjector.get(import45.Tabs,(null as any)));
    this._appEl_34.initComponent(this._Content_34_4,([] as any[]),compView_34);
    this._text_35 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_36_3 = new import28.List(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_36),this.renderer,this.parentInjector.get(import46.GestureController));
    this._text_37 = this.renderer.createText(this._el_36,'\n\n    ',(null as any));
    this._anchor_38 = this.renderer.createTemplateAnchor(this._el_36,(null as any));
    this._appEl_38 = new import2.AppElement(38,36,this,this._anchor_38);
    this._TemplateRef_38_5 = new import47.TemplateRef_(this._appEl_38,viewFactory_SchedulePage1);
    this._NgFor_38_6 = new import29.NgFor(this._appEl_38.vcRef,this._TemplateRef_38_5,this.parentInjector.get(import48.IterableDiffers),this.ref);
    this._text_39 = this.renderer.createText(this._el_36,'\n\n  ',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','item');
    this._appEl_41 = new import2.AppElement(41,34,this,this._el_41);
    var compView_41:any = import49.viewFactory_Item0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Item_41_4 = new import30.Item(this.parentInjector.get(import50.Form),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_41),this.renderer);
    this._ListHeader_41_5 = new import31.ListHeader(this.parentInjector.get(import33.Config),this.renderer,new import34.ElementRef(this._el_41),(null as any));
    this._query_Label_41_0 = new import16.QueryList<any>();
    this._query_Button_41_1 = new import16.QueryList<any>();
    this._query_Icon_41_2 = new import16.QueryList<any>();
    this._appEl_41.initComponent(this._Item_41_4,([] as any[]),compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n      No Sessions Found\n  ',(null as any));
    this._query_Label_41_0.reset(([] as any[]));
    this._Item_41_4.contentLabel = this._query_Label_41_0.first;
    compView_41.create(this._Item_41_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_42]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    compView_34.create(this._Content_34_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_35,
        this._el_36,
        this._text_40,
        this._el_41,
        this._text_43
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_44 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_9,'ngModelChange',this.eventHandler(this._handle_ngModelChange_9_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_9,'ionChange',this.eventHandler(this._handle_ionChange_9_1.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_9_3.update.subscribe(this.eventHandler(this._handle_ngModelChange_9_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    const subscription_1:any = this._Segment_9_6.ionChange.subscribe(this.eventHandler(this._handle_ionChange_9_1.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this._expr_19 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_20,'click',this.eventHandler(this._handle_click_20_0.bind(this)));
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_29,'ngModelChange',this.eventHandler(this._handle_ngModelChange_29_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_29,'ionInput',this.eventHandler(this._handle_ionInput_29_1.bind(this)));
    this._expr_27 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_29_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_29_0.bind(this)));
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    const subscription_3:any = this._Searchbar_29_7.ionInput.subscribe(this.eventHandler(this._handle_ionInput_29_1.bind(this)));
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._pipe_lowercase_0 = new import32.LowerCasePipe();
    this._expr_45 = import7.UNINITIALIZED;
    this._viewQuery_scheduleList_0.reset([this._List_36_3]);
    this.context.scheduleList = this._viewQuery_scheduleList_0.first;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._anchor_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import19.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4; }
    if (((token === import20.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5; }
    if (((token === import21.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6; }
    if (((token === import25.SegmentButton) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._SegmentButton_11_4; }
    if (((token === import25.SegmentButton) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._SegmentButton_14_4; }
    if (((token === import23.NgModel) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgModel_9_3; }
    if (((token === import51.NgControl) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgControl_9_4; }
    if (((token === import24.NgControlStatus) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgControlStatus_9_5; }
    if (((token === import25.Segment) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Segment_9_6; }
    if (((token === import22.Icon) && (22 === requestNodeIndex))) { return this._Icon_22_3; }
    if (((token === import19.Button) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Button_20_4; }
    if (((token === import21.ToolbarItem) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._ToolbarItem_18_3; }
    if (((token === import18.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Navbar_2_4; }
    if (((token === import23.NgModel) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._NgModel_29_4; }
    if (((token === import51.NgControl) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._NgControl_29_5; }
    if (((token === import24.NgControlStatus) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._NgControlStatus_29_6; }
    if (((token === import26.Searchbar) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Searchbar_29_7; }
    if (((token === import17.Toolbar) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Toolbar_27_4; }
    if (((token === import17.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Header_0_3; }
    if (((token === import47.TemplateRef) && (38 === requestNodeIndex))) { return this._TemplateRef_38_5; }
    if (((token === import29.NgFor) && (38 === requestNodeIndex))) { return this._NgFor_38_6; }
    if (((token === import28.List) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._List_36_3; }
    if (((token === import30.Item) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Item_41_4; }
    if (((token === import31.ListHeader) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._ListHeader_41_5; }
    if (((token === import27.Content) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Content_34_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_4_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_6_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    changes = (null as any);
    const currVal_9:any = this.context.segment;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgModel_9_3.model = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._NgModel_9_3.ngOnChanges(changes); }
    const currVal_17:any = 'all';
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._SegmentButton_11_4.value = currVal_17;
      this._expr_17 = currVal_17;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_11_4.ngOnInit(); }
    const currVal_19:any = 'favorites';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._SegmentButton_14_4.value = currVal_19;
      this._expr_19 = currVal_19;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_14_4.ngOnInit(); }
    const currVal_21:any = 'ios-options-outline';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._Icon_22_3.ios = currVal_21;
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = 'md-options';
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._Icon_22_3.md = currVal_22;
      this._expr_22 = currVal_22;
    }
    changes = (null as any);
    const currVal_27:any = this.context.queryText;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._NgModel_29_4.model = currVal_27;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_27,currVal_27);
      this._expr_27 = currVal_27;
    }
    if ((changes !== (null as any))) { this._NgModel_29_4.ngOnChanges(changes); }
    const currVal_34:any = 'primary';
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._Searchbar_29_7.color = currVal_34;
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = 'Search';
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this._Searchbar_29_7.placeholder = currVal_35;
      this._expr_35 = currVal_35;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Searchbar_29_7.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_34_4.ngOnInit(); }
    changes = (null as any);
    const currVal_44:any = this.context.groups;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this._NgFor_38_6.ngForOf = currVal_44;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_44,currVal_44);
      this._expr_44 = currVal_44;
    }
    if ((changes !== (null as any))) { this._NgFor_38_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_38_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4]);
        this._ToolbarItem_4_6._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_SegmentButton_9_0.dirty) {
        this._query_SegmentButton_9_0.reset([
          this._SegmentButton_11_4,
          this._SegmentButton_14_4
        ]
        );
        this._Segment_9_6._buttons = this._query_SegmentButton_9_0;
        this._query_SegmentButton_9_0.notifyOnChanges();
      }
      if (this._query_Button_18_0.dirty) {
        this._query_Button_18_0.reset([this._Button_20_4]);
        this._ToolbarItem_18_3._buttons = this._query_Button_18_0;
        this._query_Button_18_0.notifyOnChanges();
      }
      if (this._query_Button_41_1.dirty) {
        this._query_Button_41_1.reset(([] as any[]));
        this._Item_41_4._buttons = this._query_Button_41_1;
        this._query_Button_41_1.notifyOnChanges();
      }
      if (this._query_Icon_41_2.dirty) {
        this._query_Icon_41_2.reset(([] as any[]));
        this._Item_41_4._icons = this._query_Icon_41_2;
        this._query_Icon_41_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_20_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Searchbar_29_7.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_41_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_10:any = this._NgControlStatus_9_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_9,'ng-untouched',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_9_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_9,'ng-touched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_9_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_9,'ng-pristine',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_9_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_9,'ng-dirty',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_9_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_9,'ng-valid',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_9_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_9,'ng-invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_23:any = this._Icon_22_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_22,'hide',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._Toolbar_27_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_27,'statusbar-padding',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_28:any = this._NgControlStatus_29_6.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_29,'ng-untouched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_29_6.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_29,'ng-touched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_29_6.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_29,'ng-pristine',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_29_6.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_29,'ng-dirty',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_29_6.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_29,'ng-valid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_29_6.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_29,'ng-invalid',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_36:any = this._Searchbar_29_7.animated;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_29,'searchbar-animated',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._Searchbar_29_7._value;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_29,'searchbar-has-value',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._Searchbar_29_7._isActive;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_29,'searchbar-active',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._Searchbar_29_7.showCancelButton;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_29,'searchbar-show-cancel',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._Searchbar_29_7._shouldAlignLeft;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_29,'searchbar-left-aligned',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._Searchbar_29_7._sbHasFocus;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_29,'searchbar-has-focus',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._Content_34_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_34,'statusbar-padding',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = (this.context.shownSessions === 0);
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementProperty(this._el_36,'hidden',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_45:any = (this.context.shownSessions > 0);
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementProperty(this._el_41,'hidden',currVal_45);
      this._expr_45 = currVal_45;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Segment_9_6.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._NgModel_9_3.ngOnDestroy();
    this._Icon_22_3.ngOnDestroy();
    this._NgModel_29_4.ngOnDestroy();
    this._Content_34_4.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.segment = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionChange_9_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.updateSchedule()) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this._appEl_11.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_11_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this._appEl_14.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_14_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.presentFilter()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.queryText = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInput_29_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.updateSchedule()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SchedulePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SchedulePage> {
  if ((renderType_SchedulePage === (null as any))) { (renderType_SchedulePage = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_SchedulePage,{})); }
  return new _View_SchedulePage0(viewUtils,parentInjector,declarationEl);
}
class _View_SchedulePage1 extends import1.AppView<any> {
  _el_0:any;
  _ItemGroup_0_3:import30.ItemGroup;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import30.Item;
  _query_Label_2_0:import16.QueryList<any>;
  _query_Button_2_1:import16.QueryList<any>;
  _query_Icon_2_2:import16.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Label_4_3:import52.Label;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _TemplateRef_8_5:any;
  _NgFor_8_6:import29.NgFor;
  _text_9:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SchedulePage1,renderType_SchedulePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-group',(null as any));
    this._ItemGroup_0_3 = new import30.ItemGroup();
    this._text_1 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-item-divider',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item');
    this.renderer.setElementAttribute(this._el_2,'sticky','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import49.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import30.Item(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_2),this.renderer);
    this._query_Label_2_0 = new import16.QueryList<any>();
    this._query_Button_2_1 = new import16.QueryList<any>();
    this._query_Icon_2_2 = new import16.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_4_3 = new import52.Label(this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_4),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_2_0.reset([this._Label_4_3]);
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      ([] as any[]),
      ([] as any[]).concat([this._el_4]),
      ([] as any[]).concat([
        this._text_3,
        this._text_6
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_8 = new import2.AppElement(8,0,this,this._anchor_8);
    this._TemplateRef_8_5 = new import47.TemplateRef_(this._appEl_8,viewFactory_SchedulePage2);
    this._NgFor_8_6 = new import29.NgFor(this._appEl_8.vcRef,this._TemplateRef_8_5,this.parent.parentInjector.get(import48.IterableDiffers),this.parent.ref);
    this._text_9 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._anchor_8,
      this._text_9
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import52.Label) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Label_4_3; }
    if (((token === import30.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Item_2_4; }
    if (((token === import47.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import29.NgFor) && (8 === requestNodeIndex))) { return this._NgFor_8_6; }
    if (((token === import30.ItemGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ItemGroup_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_2:any = this.context.$implicit.sessions;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgFor_8_6.ngForOf = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._NgFor_8_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_8_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this.context.$implicit.hide;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'\n          ',this.context.$implicit.time,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_5,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SchedulePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SchedulePage1(viewUtils,parentInjector,declarationEl);
}
class _View_SchedulePage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ItemSliding_0_4:import53.ItemSliding;
  _query_Item_0_0:import16.QueryList<any>;
  _query_ItemOptions_0_1:import16.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import30.Item;
  _ItemContent_2_5:import30.ItemContent;
  _query_Label_2_0:import16.QueryList<any>;
  _query_Button_2_1:import16.QueryList<any>;
  _query_Icon_2_2:import16.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _ItemOptions_11_3:import53.ItemOptions;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import54.NgIf;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import54.NgIf;
  _text_16:any;
  _text_17:any;
  _pipe_lowercase_0_0:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SchedulePage2,renderType_SchedulePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-sliding',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import55.viewFactory_ItemSliding0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemSliding_0_4 = new import53.ItemSliding((<_View_SchedulePage0>this.parent.parent)._List_36_3,this.renderer,new import34.ElementRef(this._el_0),this.parent.parent.parentInjector.get(import44.NgZone));
    this._query_Item_0_0 = new import16.QueryList<any>();
    this._query_ItemOptions_0_1 = new import16.QueryList<any>();
    this._appEl_0.initComponent(this._ItemSliding_0_4,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'ion-item','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import49.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import30.Item(this.parent.parent.parentInjector.get(import50.Form),this.parent.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import30.ItemContent();
    this._query_Label_2_0 = new import16.QueryList<any>();
    this._query_Button_2_1 = new import16.QueryList<any>();
    this._query_Icon_2_2 = new import16.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6,
        this._el_7,
        this._text_9
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n\n        ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-item-options',(null as any));
    this._ItemOptions_11_3 = new import53.ItemOptions(new import34.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._appEl_13 = new import2.AppElement(13,11,this,this._anchor_13);
    this._TemplateRef_13_5 = new import47.TemplateRef_(this._appEl_13,viewFactory_SchedulePage3);
    this._NgIf_13_6 = new import54.NgIf(this._appEl_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._appEl_15 = new import2.AppElement(15,11,this,this._anchor_15);
    this._TemplateRef_15_5 = new import47.TemplateRef_(this._appEl_15,viewFactory_SchedulePage4);
    this._NgIf_15_6 = new import54.NgIf(this._appEl_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n\n      ',(null as any));
    this._query_Item_0_0.reset([this._Item_2_4]);
    this._ItemSliding_0_4.item = this._query_Item_0_0.first;
    compView_0.create(this._ItemSliding_0_4,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]).concat([this._el_11])
    ]
    ,(null as any));
    this._pipe_lowercase_0_0 = import4.pureProxy1((<_View_SchedulePage0>this.parent.parent)._pipe_lowercase_0.transform.bind((<_View_SchedulePage0>this.parent.parent)._pipe_lowercase_0));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._text_17
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import30.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Item_2_4; }
    if (((token === import30.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ItemContent_2_5; }
    if (((token === import47.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import54.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6; }
    if (((token === import47.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import54.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6; }
    if (((token === import53.ItemOptions) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ItemOptions_11_3; }
    if (((token === import53.ItemSliding) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._ItemSliding_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_5:any = (this.parent.parent.context.segment === 'all');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_13_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = (this.parent.parent.context.segment === 'favorites');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_15_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_ItemOptions_0_1.dirty) {
        this._query_ItemOptions_0_1.reset([this._ItemOptions_11_3]);
        this._ItemSliding_0_4._itemOptions = this._query_ItemOptions_0_1;
        this._query_ItemOptions_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    valUnwrapper.reset();
    const currVal_0:any = valUnwrapper.unwrap(import4.castByValue(this._pipe_lowercase_0_0,(<_View_SchedulePage0>this.parent.parent)._pipe_lowercase_0.transform)(this.context.$implicit.tracks[0]));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setElementAttribute(this._el_0,'track',((currVal_0 == (null as any))? (null as any): currVal_0.toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.$implicit.hide;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_5,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(3,'\n            ',this.context.$implicit.timeStart,' —\n            ',this.context.$implicit.timeEnd,':\n            ',this.context.$implicit.location,'\n          ');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_8,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.goToSessionDetail(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_SchedulePage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SchedulePage2(viewUtils,parentInjector,declarationEl);
}
class _View_SchedulePage3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Button_0_4:import19.Button;
  _text_1:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SchedulePage3,renderType_SchedulePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','favorite');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import37.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import19.Button((null as any),'',this.parent.parent.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n            Favorite\n          ',(null as any));
    compView_0.create(this._Button_0_4,[([] as any[]).concat([this._text_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = 'favorite';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_0_4.color = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.addFavorite((<_View_SchedulePage2>this.parent)._ItemSliding_0_4,this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_SchedulePage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SchedulePage3(viewUtils,parentInjector,declarationEl);
}
class _View_SchedulePage4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Button_0_4:import19.Button;
  _text_1:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SchedulePage4,renderType_SchedulePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','danger');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import37.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import19.Button((null as any),'',this.parent.parent.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n            Remove\n          ',(null as any));
    compView_0.create(this._Button_0_4,[([] as any[]).concat([this._text_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_0_4.color = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.removeFavorite((<_View_SchedulePage2>this.parent)._ItemSliding_0_4,this.parent.context.$implicit,'Remove Favorite')) !== false);
    return (true && pd_0);
  }
}
function viewFactory_SchedulePage4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SchedulePage4(viewUtils,parentInjector,declarationEl);
}