/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './app.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/util/events';
import * as import9 from '../providers/user-data';
import * as import10 from 'ionic-angular/components/menu/menu-controller';
import * as import11 from 'ionic-angular/platform/platform';
import * as import12 from '../providers/conference-data';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from 'ionic-angular/components/menu/menu';
import * as import17 from 'ionic-angular/components/toolbar/toolbar';
import * as import18 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import19 from 'ionic-angular/components/content/content';
import * as import20 from 'ionic-angular/components/list/list';
import * as import21 from 'ionic-angular/components/item/item';
import * as import22 from 'ionic-angular/components/list/list-header';
import * as import23 from '@angular/common/src/directives/ng_for';
import * as import24 from 'ionic-angular/components/nav/nav';
import * as import25 from '../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from 'ionic-angular/util/keyboard';
import * as import29 from '@angular/core/src/zone/ng_zone';
import * as import30 from 'ionic-angular/gestures/gesture-controller';
import * as import31 from 'ionic-angular/navigation/view-controller';
import * as import32 from '../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import33 from '../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import34 from 'ionic-angular/components/navbar/navbar';
import * as import35 from '../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import36 from 'ionic-angular/components/app/app';
import * as import37 from 'ionic-angular/components/tabs/tabs';
import * as import38 from '../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import39 from 'ionic-angular/util/form';
import * as import40 from '@angular/core/src/linker/template_ref';
import * as import41 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import42 from '../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import43 from 'ionic-angular/navigation/nav-controller-base';
import * as import44 from '@angular/core/src/linker/component_factory_resolver';
import * as import45 from 'ionic-angular/transitions/transition-controller';
import * as import46 from 'ionic-angular/navigation/deep-linker';
import * as import47 from 'ionic-angular/components/menu/menu-close';
import * as import48 from 'ionic-angular/components/icon/icon';
var renderType_ConferenceApp_Host:import0.RenderComponentType = (null as any);
class _View_ConferenceApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ConferenceApp_0_4:import3.ConferenceApp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConferenceApp_Host0,renderType_ConferenceApp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ConferenceApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ConferenceApp_0_4 = new import3.ConferenceApp(this.parentInjector.get(import8.Events),this.parentInjector.get(import9.UserData),this.parentInjector.get(import10.MenuController),this.parentInjector.get(import11.Platform),this.parentInjector.get(import12.ConferenceData));
    this._appEl_0.initComponent(this._ConferenceApp_0_4,([] as any[]),compView_0);
    compView_0.create(this._ConferenceApp_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ConferenceApp) && (0 === requestNodeIndex))) { return this._ConferenceApp_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ConferenceApp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ConferenceApp_Host === (null as any))) { (renderType_ConferenceApp_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ConferenceApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const ConferenceAppNgFactory:import14.ComponentFactory<import3.ConferenceApp> = new import14.ComponentFactory<import3.ConferenceApp>('ng-component',viewFactory_ConferenceApp_Host0,import3.ConferenceApp);
const styles_ConferenceApp:any[] = ([] as any[]);
var renderType_ConferenceApp:import0.RenderComponentType = (null as any);
class _View_ConferenceApp0 extends import1.AppView<import3.ConferenceApp> {
  _viewQuery_Nav_0:import15.QueryList<any>;
  _text_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Menu_2_4:import16.Menu;
  _query_Content_2_0:import15.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Header_4_3:import17.Header;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _Toolbar_6_4:import17.Toolbar;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _ToolbarTitle_8_4:import18.ToolbarTitle;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _Content_13_4:import19.Content;
  _text_14:any;
  _el_15:any;
  _List_15_3:import20.List;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _Item_17_4:import21.Item;
  _ListHeader_17_5:import22.ListHeader;
  _query_Label_17_0:import15.QueryList<any>;
  _query_Button_17_1:import15.QueryList<any>;
  _query_Icon_17_2:import15.QueryList<any>;
  _text_18:any;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _TemplateRef_20_5:any;
  _NgFor_20_6:import23.NgFor;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _List_23_3:import20.List;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _Item_25_4:import21.Item;
  _ListHeader_25_5:import22.ListHeader;
  _query_Label_25_0:import15.QueryList<any>;
  _query_Button_25_1:import15.QueryList<any>;
  _query_Icon_25_2:import15.QueryList<any>;
  _text_26:any;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _TemplateRef_28_5:any;
  _NgFor_28_6:import23.NgFor;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _Menu_34_4:import16.Menu;
  _query_Content_34_0:import15.QueryList<any>;
  _text_35:any;
  _el_36:any;
  _Header_36_3:import17.Header;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import2.AppElement;
  _Toolbar_38_4:import17.Toolbar;
  _text_39:any;
  _el_40:any;
  /*private*/ _appEl_40:import2.AppElement;
  _ToolbarTitle_40_4:import18.ToolbarTitle;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  /*private*/ _appEl_45:import2.AppElement;
  _Content_45_4:import19.Content;
  _text_46:any;
  _el_47:any;
  _List_47_3:import20.List;
  _text_48:any;
  _el_49:any;
  /*private*/ _appEl_49:import2.AppElement;
  _Item_49_4:import21.Item;
  _ListHeader_49_5:import22.ListHeader;
  _query_Label_49_0:import15.QueryList<any>;
  _query_Button_49_1:import15.QueryList<any>;
  _query_Icon_49_2:import15.QueryList<any>;
  _text_50:any;
  _text_51:any;
  _anchor_52:any;
  /*private*/ _appEl_52:import2.AppElement;
  _TemplateRef_52_5:any;
  _NgFor_52_6:import23.NgFor;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _List_55_3:import20.List;
  _text_56:any;
  _el_57:any;
  /*private*/ _appEl_57:import2.AppElement;
  _Item_57_4:import21.Item;
  _ListHeader_57_5:import22.ListHeader;
  _query_Label_57_0:import15.QueryList<any>;
  _query_Button_57_1:import15.QueryList<any>;
  _query_Icon_57_2:import15.QueryList<any>;
  _text_58:any;
  _text_59:any;
  _anchor_60:any;
  /*private*/ _appEl_60:import2.AppElement;
  _TemplateRef_60_5:any;
  _NgFor_60_6:import23.NgFor;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  /*private*/ _appEl_66:import2.AppElement;
  _Nav_66_4:import24.Nav;
  _text_67:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConferenceApp0,renderType_ConferenceApp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Nav_0 = new import15.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_2,'id','loggedOutMenu');
    this.renderer.setElementAttribute(this._el_2,'role','navigation');
    this._appEl_2 = new import2.AppElement(2,(null as any),this,this._el_2);
    var compView_2:any = import25.viewFactory_Menu0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Menu_2_4 = new import16.Menu(this.parentInjector.get(import10.MenuController),new import26.ElementRef(this._el_2),this.parentInjector.get(import27.Config),this.parentInjector.get(import11.Platform),this.renderer,this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import30.GestureController));
    this._query_Content_2_0 = new import15.QueryList<any>();
    this._appEl_2.initComponent(this._Menu_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-header',(null as any));
    this._Header_4_3 = new import17.Header(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import31.ViewController,(null as any)));
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','toolbar');
    this._appEl_6 = new import2.AppElement(6,4,this,this._el_6);
    var compView_6:any = import32.viewFactory_Toolbar0(this.viewUtils,this.injector(6),this._appEl_6);
    this._Toolbar_6_4 = new import17.Toolbar(this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_6),this.renderer);
    this._appEl_6.initComponent(this._Toolbar_6_4,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_8 = new import2.AppElement(8,6,this,this._el_8);
    var compView_8:any = import33.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(8),this._appEl_8);
    this._ToolbarTitle_8_4 = new import18.ToolbarTitle(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_8),this.renderer,this._Toolbar_6_4,this.parentInjector.get(import34.Navbar,(null as any)));
    this._appEl_8.initComponent(this._ToolbarTitle_8_4,([] as any[]),compView_8);
    this._text_9 = this.renderer.createText((null as any),'Menu',(null as any));
    compView_8.create(this._ToolbarTitle_8_4,[([] as any[]).concat([this._text_9])],(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_6.create(this._Toolbar_6_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_7,
        this._el_8,
        this._text_10
      ]
      )
    ]
    ,(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','outer-content');
    this._appEl_13 = new import2.AppElement(13,2,this,this._el_13);
    var compView_13:any = import35.viewFactory_Content0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Content_13_4 = new import19.Content(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import36.App),this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import37.Tabs,(null as any)));
    this._appEl_13.initComponent(this._Content_13_4,([] as any[]),compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_15_3 = new import20.List(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_15),this.renderer,this.parentInjector.get(import30.GestureController));
    this._text_16 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','item');
    this._appEl_17 = new import2.AppElement(17,15,this,this._el_17);
    var compView_17:any = import38.viewFactory_Item0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Item_17_4 = new import21.Item(this.parentInjector.get(import39.Form),this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_17),this.renderer);
    this._ListHeader_17_5 = new import22.ListHeader(this.parentInjector.get(import27.Config),this.renderer,new import26.ElementRef(this._el_17),(null as any));
    this._query_Label_17_0 = new import15.QueryList<any>();
    this._query_Button_17_1 = new import15.QueryList<any>();
    this._query_Icon_17_2 = new import15.QueryList<any>();
    this._appEl_17.initComponent(this._Item_17_4,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n        Navigate\n      ',(null as any));
    this._query_Label_17_0.reset(([] as any[]));
    this._Item_17_4.contentLabel = this._query_Label_17_0.first;
    compView_17.create(this._Item_17_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_18]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._appEl_20 = new import2.AppElement(20,15,this,this._anchor_20);
    this._TemplateRef_20_5 = new import40.TemplateRef_(this._appEl_20,viewFactory_ConferenceApp1);
    this._NgFor_20_6 = new import23.NgFor(this._appEl_20.vcRef,this._TemplateRef_20_5,this.parentInjector.get(import41.IterableDiffers),this.ref);
    this._text_21 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_23_3 = new import20.List(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import30.GestureController));
    this._text_24 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','item');
    this._appEl_25 = new import2.AppElement(25,23,this,this._el_25);
    var compView_25:any = import38.viewFactory_Item0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Item_25_4 = new import21.Item(this.parentInjector.get(import39.Form),this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_25),this.renderer);
    this._ListHeader_25_5 = new import22.ListHeader(this.parentInjector.get(import27.Config),this.renderer,new import26.ElementRef(this._el_25),(null as any));
    this._query_Label_25_0 = new import15.QueryList<any>();
    this._query_Button_25_1 = new import15.QueryList<any>();
    this._query_Icon_25_2 = new import15.QueryList<any>();
    this._appEl_25.initComponent(this._Item_25_4,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n        Account\n      ',(null as any));
    this._query_Label_25_0.reset(([] as any[]));
    this._Item_25_4.contentLabel = this._query_Label_25_0.first;
    compView_25.create(this._Item_25_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_26]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_23,(null as any));
    this._appEl_28 = new import2.AppElement(28,23,this,this._anchor_28);
    this._TemplateRef_28_5 = new import40.TemplateRef_(this._appEl_28,viewFactory_ConferenceApp2);
    this._NgFor_28_6 = new import23.NgFor(this._appEl_28.vcRef,this._TemplateRef_28_5,this.parentInjector.get(import41.IterableDiffers),this.ref);
    this._text_29 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_13.create(this._Content_13_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_14,
        this._el_15,
        this._text_22,
        this._el_23,
        this._text_30
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._query_Content_2_0.reset([this._Content_13_4]);
    this._Menu_2_4.menuContent = this._query_Content_2_0.first;
      compView_2.create(this._Menu_2_4,[([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_12,
        this._el_13,
        this._text_31
      ]
    )],(null as any));
    this._text_32 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_33 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_34 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_34,'id','loggedInMenu');
    this.renderer.setElementAttribute(this._el_34,'role','navigation');
    this._appEl_34 = new import2.AppElement(34,(null as any),this,this._el_34);
    var compView_34:any = import25.viewFactory_Menu0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Menu_34_4 = new import16.Menu(this.parentInjector.get(import10.MenuController),new import26.ElementRef(this._el_34),this.parentInjector.get(import27.Config),this.parentInjector.get(import11.Platform),this.renderer,this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import30.GestureController));
    this._query_Content_34_0 = new import15.QueryList<any>();
    this._appEl_34.initComponent(this._Menu_34_4,([] as any[]),compView_34);
    this._text_35 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'ion-header',(null as any));
    this._Header_36_3 = new import17.Header(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_36),this.renderer,this.parentInjector.get(import31.ViewController,(null as any)));
    this._text_37 = this.renderer.createText(this._el_36,'\n    ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','toolbar');
    this._appEl_38 = new import2.AppElement(38,36,this,this._el_38);
    var compView_38:any = import32.viewFactory_Toolbar0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Toolbar_38_4 = new import17.Toolbar(this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_38),this.renderer);
    this._appEl_38.initComponent(this._Toolbar_38_4,([] as any[]),compView_38);
    this._text_39 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_40 = new import2.AppElement(40,38,this,this._el_40);
    var compView_40:any = import33.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(40),this._appEl_40);
    this._ToolbarTitle_40_4 = new import18.ToolbarTitle(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_40),this.renderer,this._Toolbar_38_4,this.parentInjector.get(import34.Navbar,(null as any)));
    this._appEl_40.initComponent(this._ToolbarTitle_40_4,([] as any[]),compView_40);
    this._text_41 = this.renderer.createText((null as any),'Menu',(null as any));
    compView_40.create(this._ToolbarTitle_40_4,[([] as any[]).concat([this._text_41])],(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_38.create(this._Toolbar_38_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_39,
        this._el_40,
        this._text_42
      ]
      )
    ]
    ,(null as any));
    this._text_43 = this.renderer.createText(this._el_36,'\n  ',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_45 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','outer-content');
    this._appEl_45 = new import2.AppElement(45,34,this,this._el_45);
    var compView_45:any = import35.viewFactory_Content0(this.viewUtils,this.injector(45),this._appEl_45);
    this._Content_45_4 = new import19.Content(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_45),this.renderer,this.parentInjector.get(import36.App),this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import37.Tabs,(null as any)));
    this._appEl_45.initComponent(this._Content_45_4,([] as any[]),compView_45);
    this._text_46 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_47_3 = new import20.List(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_47),this.renderer,this.parentInjector.get(import30.GestureController));
    this._text_48 = this.renderer.createText(this._el_47,'\n      ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_47,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','item');
    this._appEl_49 = new import2.AppElement(49,47,this,this._el_49);
    var compView_49:any = import38.viewFactory_Item0(this.viewUtils,this.injector(49),this._appEl_49);
    this._Item_49_4 = new import21.Item(this.parentInjector.get(import39.Form),this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_49),this.renderer);
    this._ListHeader_49_5 = new import22.ListHeader(this.parentInjector.get(import27.Config),this.renderer,new import26.ElementRef(this._el_49),(null as any));
    this._query_Label_49_0 = new import15.QueryList<any>();
    this._query_Button_49_1 = new import15.QueryList<any>();
    this._query_Icon_49_2 = new import15.QueryList<any>();
    this._appEl_49.initComponent(this._Item_49_4,([] as any[]),compView_49);
    this._text_50 = this.renderer.createText((null as any),'\n        Navigate\n      ',(null as any));
    this._query_Label_49_0.reset(([] as any[]));
    this._Item_49_4.contentLabel = this._query_Label_49_0.first;
    compView_49.create(this._Item_49_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_50]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_51 = this.renderer.createText(this._el_47,'\n      ',(null as any));
    this._anchor_52 = this.renderer.createTemplateAnchor(this._el_47,(null as any));
    this._appEl_52 = new import2.AppElement(52,47,this,this._anchor_52);
    this._TemplateRef_52_5 = new import40.TemplateRef_(this._appEl_52,viewFactory_ConferenceApp3);
    this._NgFor_52_6 = new import23.NgFor(this._appEl_52.vcRef,this._TemplateRef_52_5,this.parentInjector.get(import41.IterableDiffers),this.ref);
    this._text_53 = this.renderer.createText(this._el_47,'\n    ',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_55 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_55_3 = new import20.List(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_55),this.renderer,this.parentInjector.get(import30.GestureController));
    this._text_56 = this.renderer.createText(this._el_55,'\n      ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_55,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','item');
    this._appEl_57 = new import2.AppElement(57,55,this,this._el_57);
    var compView_57:any = import38.viewFactory_Item0(this.viewUtils,this.injector(57),this._appEl_57);
    this._Item_57_4 = new import21.Item(this.parentInjector.get(import39.Form),this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_57),this.renderer);
    this._ListHeader_57_5 = new import22.ListHeader(this.parentInjector.get(import27.Config),this.renderer,new import26.ElementRef(this._el_57),(null as any));
    this._query_Label_57_0 = new import15.QueryList<any>();
    this._query_Button_57_1 = new import15.QueryList<any>();
    this._query_Icon_57_2 = new import15.QueryList<any>();
    this._appEl_57.initComponent(this._Item_57_4,([] as any[]),compView_57);
    this._text_58 = this.renderer.createText((null as any),'\n        Account\n      ',(null as any));
    this._query_Label_57_0.reset(([] as any[]));
    this._Item_57_4.contentLabel = this._query_Label_57_0.first;
    compView_57.create(this._Item_57_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_58]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_59 = this.renderer.createText(this._el_55,'\n      ',(null as any));
    this._anchor_60 = this.renderer.createTemplateAnchor(this._el_55,(null as any));
    this._appEl_60 = new import2.AppElement(60,55,this,this._anchor_60);
    this._TemplateRef_60_5 = new import40.TemplateRef_(this._appEl_60,viewFactory_ConferenceApp4);
    this._NgFor_60_6 = new import23.NgFor(this._appEl_60.vcRef,this._TemplateRef_60_5,this.parentInjector.get(import41.IterableDiffers),this.ref);
    this._text_61 = this.renderer.createText(this._el_55,'\n    ',(null as any));
    this._text_62 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    compView_45.create(this._Content_45_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_46,
        this._el_47,
        this._text_54,
        this._el_55,
        this._text_62
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_63 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._query_Content_34_0.reset([this._Content_45_4]);
    this._Menu_34_4.menuContent = this._query_Content_34_0.first;
      compView_34.create(this._Menu_34_4,[([] as any[]).concat([
        this._text_35,
        this._el_36,
        this._text_44,
        this._el_45,
        this._text_63
      ]
    )],(null as any));
    this._text_64 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._text_65 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_66 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this.renderer.setElementAttribute(this._el_66,'swipeBackEnabled','false');
    this._appEl_66 = new import2.AppElement(66,(null as any),this,this._el_66);
    var compView_66:any = import42.viewFactory_Nav0(this.viewUtils,this.injector(66),this._appEl_66);
    this._Nav_66_4 = new import24.Nav(this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import43.NavControllerBase,(null as any)),this.parentInjector.get(import36.App),this.parentInjector.get(import27.Config),this.parentInjector.get(import28.Keyboard),new import26.ElementRef(this._el_66),this.parentInjector.get(import29.NgZone),this.renderer,this.parentInjector.get(import44.ComponentFactoryResolver),this.parentInjector.get(import30.GestureController),this.parentInjector.get(import45.TransitionController),this.parentInjector.get(import46.DeepLinker,(null as any)));
    this._appEl_66.initComponent(this._Nav_66_4,([] as any[]),compView_66);
    compView_66.create(this._Nav_66_4,([] as any[]),(null as any));
    this._text_67 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._viewQuery_Nav_0.reset([this._Nav_66_4]);
    this.context.nav = this._viewQuery_Nav_0.first;
    this.init(([] as any[]),[
      this._text_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._anchor_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._anchor_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.ToolbarTitle) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ToolbarTitle_8_4; }
    if (((token === import17.Toolbar) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Toolbar_6_4; }
    if (((token === import17.Header) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Header_4_3; }
    if (((token === import21.Item) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Item_17_4; }
    if (((token === import22.ListHeader) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._ListHeader_17_5; }
    if (((token === import40.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import23.NgFor) && (20 === requestNodeIndex))) { return this._NgFor_20_6; }
    if (((token === import20.List) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._List_15_3; }
    if (((token === import21.Item) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Item_25_4; }
    if (((token === import22.ListHeader) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ListHeader_25_5; }
    if (((token === import40.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import23.NgFor) && (28 === requestNodeIndex))) { return this._NgFor_28_6; }
    if (((token === import20.List) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._List_23_3; }
    if (((token === import19.Content) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Content_13_4; }
    if (((token === import16.Menu) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Menu_2_4; }
    if (((token === import18.ToolbarTitle) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._ToolbarTitle_40_4; }
    if (((token === import17.Toolbar) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Toolbar_38_4; }
    if (((token === import17.Header) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Header_36_3; }
    if (((token === import21.Item) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Item_49_4; }
    if (((token === import22.ListHeader) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._ListHeader_49_5; }
    if (((token === import40.TemplateRef) && (52 === requestNodeIndex))) { return this._TemplateRef_52_5; }
    if (((token === import23.NgFor) && (52 === requestNodeIndex))) { return this._NgFor_52_6; }
    if (((token === import20.List) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._List_47_3; }
    if (((token === import21.Item) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Item_57_4; }
    if (((token === import22.ListHeader) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._ListHeader_57_5; }
    if (((token === import40.TemplateRef) && (60 === requestNodeIndex))) { return this._TemplateRef_60_5; }
    if (((token === import23.NgFor) && (60 === requestNodeIndex))) { return this._NgFor_60_6; }
    if (((token === import20.List) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._List_55_3; }
    if (((token === import19.Content) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 62)))) { return this._Content_45_4; }
    if (((token === import16.Menu) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._Menu_34_4; }
    if (((token === import24.Nav) && (66 === requestNodeIndex))) { return this._Nav_66_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changed = false;
    const currVal_0:any = this._Nav_66_4;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Menu_2_4.content = currVal_0;
      changed = true;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'loggedOutMenu';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Menu_2_4.id = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Menu_2_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_13_4.ngOnInit(); }
    changes = (null as any);
    const currVal_4:any = this.context.appPages;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgFor_20_6.ngForOf = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgFor_20_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_20_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_5:any = this.context.loggedOutPages;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgFor_28_6.ngForOf = currVal_5;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    if ((changes !== (null as any))) { this._NgFor_28_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_28_6.ngDoCheck(); }
    changed = false;
    const currVal_6:any = this._Nav_66_4;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Menu_34_4.content = currVal_6;
      changed = true;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = 'loggedInMenu';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Menu_34_4.id = currVal_7;
      changed = true;
      this._expr_7 = currVal_7;
    }
    if (changed) { this._appEl_34.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Menu_34_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_45_4.ngOnInit(); }
    changes = (null as any);
    const currVal_10:any = this.context.appPages;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgFor_52_6.ngForOf = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgFor_52_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_52_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_11:any = this.context.loggedInPages;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgFor_60_6.ngForOf = currVal_11;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_11,currVal_11);
      this._expr_11 = currVal_11;
    }
    if ((changes !== (null as any))) { this._NgFor_60_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_60_6.ngDoCheck(); }
    const currVal_12:any = this.context.rootPage;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Nav_66_4.root = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = 'false';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._Nav_66_4.swipeBackEnabled = currVal_13;
      this._expr_13 = currVal_13;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_17_1.dirty) {
        this._query_Button_17_1.reset(([] as any[]));
        this._Item_17_4._buttons = this._query_Button_17_1;
        this._query_Button_17_1.notifyOnChanges();
      }
      if (this._query_Icon_17_2.dirty) {
        this._query_Icon_17_2.reset(([] as any[]));
        this._Item_17_4._icons = this._query_Icon_17_2;
        this._query_Icon_17_2.notifyOnChanges();
      }
      if (this._query_Button_25_1.dirty) {
        this._query_Button_25_1.reset(([] as any[]));
        this._Item_25_4._buttons = this._query_Button_25_1;
        this._query_Button_25_1.notifyOnChanges();
      }
      if (this._query_Icon_25_2.dirty) {
        this._query_Icon_25_2.reset(([] as any[]));
        this._Item_25_4._icons = this._query_Icon_25_2;
        this._query_Icon_25_2.notifyOnChanges();
      }
      if (this._query_Button_49_1.dirty) {
        this._query_Button_49_1.reset(([] as any[]));
        this._Item_49_4._buttons = this._query_Button_49_1;
        this._query_Button_49_1.notifyOnChanges();
      }
      if (this._query_Icon_49_2.dirty) {
        this._query_Icon_49_2.reset(([] as any[]));
        this._Item_49_4._icons = this._query_Icon_49_2;
        this._query_Icon_49_2.notifyOnChanges();
      }
      if (this._query_Button_57_1.dirty) {
        this._query_Button_57_1.reset(([] as any[]));
        this._Item_57_4._buttons = this._query_Button_57_1;
        this._query_Button_57_1.notifyOnChanges();
      }
      if (this._query_Icon_57_2.dirty) {
        this._query_Icon_57_2.reset(([] as any[]));
        this._Item_57_4._icons = this._query_Icon_57_2;
        this._query_Icon_57_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_17_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_25_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_49_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_57_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._Toolbar_6_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_6,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_13_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_13,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_8:any = this._Toolbar_38_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_38,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._Content_45_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_45,'statusbar-padding',currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_66_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_13_4.ngOnDestroy();
    this._Menu_2_4.ngOnDestroy();
    this._Content_45_4.ngOnDestroy();
    this._Menu_34_4.ngOnDestroy();
  }
}
export function viewFactory_ConferenceApp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ConferenceApp> {
  if ((renderType_ConferenceApp === (null as any))) { (renderType_ConferenceApp = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_ConferenceApp,{})); }
  return new _View_ConferenceApp0(viewUtils,parentInjector,declarationEl);
}
class _View_ConferenceApp1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import21.Item;
  _ItemContent_0_5:import21.ItemContent;
  _MenuClose_0_6:import47.MenuClose;
  _query_Label_0_0:import15.QueryList<any>;
  _query_Button_0_1:import15.QueryList<any>;
  _query_Icon_0_2:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import48.Icon;
  _text_3:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConferenceApp1,renderType_ConferenceApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import38.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Item(this.parent.parentInjector.get(import39.Form),this.parent.parentInjector.get(import27.Config),new import26.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.ItemContent();
    this._MenuClose_0_6 = new import47.MenuClose(this.parent.parentInjector.get(import10.MenuController));
    this._query_Label_0_0 = new import15.QueryList<any>();
    this._query_Button_0_1 = new import15.QueryList<any>();
    this._query_Icon_0_2 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import48.Icon(this.parent.parentInjector.get(import27.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import48.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    if (((token === import21.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_0_4; }
    if (((token === import21.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_0_5; }
    if (((token === import47.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuClose_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._MenuClose_0_6.menuClose = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.$implicit.icon;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_2_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_ConferenceApp1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ConferenceApp1(viewUtils,parentInjector,declarationEl);
}
class _View_ConferenceApp2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import21.Item;
  _ItemContent_0_5:import21.ItemContent;
  _MenuClose_0_6:import47.MenuClose;
  _query_Label_0_0:import15.QueryList<any>;
  _query_Button_0_1:import15.QueryList<any>;
  _query_Icon_0_2:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import48.Icon;
  _text_3:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConferenceApp2,renderType_ConferenceApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import38.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Item(this.parent.parentInjector.get(import39.Form),this.parent.parentInjector.get(import27.Config),new import26.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.ItemContent();
    this._MenuClose_0_6 = new import47.MenuClose(this.parent.parentInjector.get(import10.MenuController));
    this._query_Label_0_0 = new import15.QueryList<any>();
    this._query_Button_0_1 = new import15.QueryList<any>();
    this._query_Icon_0_2 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import48.Icon(this.parent.parentInjector.get(import27.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import48.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    if (((token === import21.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_0_4; }
    if (((token === import21.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_0_5; }
    if (((token === import47.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuClose_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._MenuClose_0_6.menuClose = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.$implicit.icon;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_2_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_ConferenceApp2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ConferenceApp2(viewUtils,parentInjector,declarationEl);
}
class _View_ConferenceApp3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import21.Item;
  _ItemContent_0_5:import21.ItemContent;
  _MenuClose_0_6:import47.MenuClose;
  _query_Label_0_0:import15.QueryList<any>;
  _query_Button_0_1:import15.QueryList<any>;
  _query_Icon_0_2:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import48.Icon;
  _text_3:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConferenceApp3,renderType_ConferenceApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import38.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Item(this.parent.parentInjector.get(import39.Form),this.parent.parentInjector.get(import27.Config),new import26.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.ItemContent();
    this._MenuClose_0_6 = new import47.MenuClose(this.parent.parentInjector.get(import10.MenuController));
    this._query_Label_0_0 = new import15.QueryList<any>();
    this._query_Button_0_1 = new import15.QueryList<any>();
    this._query_Icon_0_2 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import48.Icon(this.parent.parentInjector.get(import27.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import48.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    if (((token === import21.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_0_4; }
    if (((token === import21.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_0_5; }
    if (((token === import47.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuClose_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._MenuClose_0_6.menuClose = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.$implicit.icon;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_2_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_ConferenceApp3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ConferenceApp3(viewUtils,parentInjector,declarationEl);
}
class _View_ConferenceApp4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import21.Item;
  _ItemContent_0_5:import21.ItemContent;
  _MenuClose_0_6:import47.MenuClose;
  _query_Label_0_0:import15.QueryList<any>;
  _query_Button_0_1:import15.QueryList<any>;
  _query_Icon_0_2:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import48.Icon;
  _text_3:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConferenceApp4,renderType_ConferenceApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import38.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Item(this.parent.parentInjector.get(import39.Form),this.parent.parentInjector.get(import27.Config),new import26.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.ItemContent();
    this._MenuClose_0_6 = new import47.MenuClose(this.parent.parentInjector.get(import10.MenuController));
    this._query_Label_0_0 = new import15.QueryList<any>();
    this._query_Button_0_1 = new import15.QueryList<any>();
    this._query_Icon_0_2 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import48.Icon(this.parent.parentInjector.get(import27.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import48.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    if (((token === import21.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_0_4; }
    if (((token === import21.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_0_5; }
    if (((token === import47.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuClose_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._MenuClose_0_6.menuClose = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.$implicit.icon;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_2_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_ConferenceApp4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ConferenceApp4(viewUtils,parentInjector,declarationEl);
}