/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './about';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/components/popover/popover';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/toolbar/toolbar';
import * as import12 from 'ionic-angular/components/navbar/navbar';
import * as import13 from 'ionic-angular/components/button/button';
import * as import14 from 'ionic-angular/components/menu/menu-toggle';
import * as import15 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from 'ionic-angular/components/icon/icon';
import * as import18 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import19 from 'ionic-angular/components/content/content';
import * as import20 from 'ionic-angular/components/list/list';
import * as import21 from 'ionic-angular/components/item/item';
import * as import22 from 'ionic-angular/components/label/label';
import * as import23 from 'ionic-angular/components/datetime/datetime';
import * as import24 from '@angular/forms/src/directives/ng_model';
import * as import25 from '@angular/forms/src/directives/ng_control_status';
import * as import26 from 'ionic-angular/components/select/select';
import * as import27 from 'ionic-angular/components/option/option';
import * as import28 from 'ionic-angular/config/config';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import32 from 'ionic-angular/components/app/app';
import * as import33 from 'ionic-angular/navigation/nav-controller';
import * as import34 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import35 from 'ionic-angular/components/menu/menu-controller';
import * as import36 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import37 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import38 from 'ionic-angular/util/keyboard';
import * as import39 from '@angular/core/src/zone/ng_zone';
import * as import40 from 'ionic-angular/components/tabs/tabs';
import * as import41 from 'ionic-angular/gestures/gesture-controller';
import * as import42 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import43 from 'ionic-angular/util/form';
import * as import44 from '../../node_modules/ionic-angular/components/datetime/datetime.ngfactory';
import * as import45 from 'ionic-angular/components/picker/picker';
import * as import46 from '../../node_modules/ionic-angular/components/select/select.ngfactory';
import * as import47 from '@angular/forms/src/directives/control_value_accessor';
import * as import48 from '@angular/forms/src/directives/ng_control';
var renderType_AboutPage_Host:import0.RenderComponentType = (null as any);
class _View_AboutPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AboutPage_0_4:import3.AboutPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AboutPage_Host0,renderType_AboutPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-about',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AboutPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AboutPage_0_4 = new import3.AboutPage(this.parentInjector.get(import8.PopoverController));
    this._appEl_0.initComponent(this._AboutPage_0_4,([] as any[]),compView_0);
    compView_0.create(this._AboutPage_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AboutPage) && (0 === requestNodeIndex))) { return this._AboutPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_AboutPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AboutPage_Host === (null as any))) { (renderType_AboutPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AboutPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const AboutPageNgFactory:import10.ComponentFactory<import3.AboutPage> = new import10.ComponentFactory<import3.AboutPage>('page-about',viewFactory_AboutPage_Host0,import3.AboutPage);
const styles_AboutPage:any[] = ([] as any[]);
var renderType_AboutPage:import0.RenderComponentType = (null as any);
class _View_AboutPage0 extends import1.AppView<import3.AboutPage> {
  _el_0:any;
  _Header_0_3:import11.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import12.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import13.Button;
  _MenuToggle_4_5:import14.MenuToggle;
  _ToolbarItem_4_6:import15.ToolbarItem;
  _query_Button_4_0:import16.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import17.Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ToolbarTitle_9_4:import18.ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _ToolbarItem_12_3:import15.ToolbarItem;
  _query_Button_12_0:import16.QueryList<any>;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Button_14_4:import13.Button;
  _text_15:any;
  _el_16:any;
  _Icon_16_3:import17.Icon;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _Content_22_4:import19.Content;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _List_34_3:import20.List;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import2.AppElement;
  _Item_36_4:import21.Item;
  _ItemContent_36_5:import21.ItemContent;
  _query_Label_36_0:import16.QueryList<any>;
  _query_Button_36_1:import16.QueryList<any>;
  _query_Icon_36_2:import16.QueryList<any>;
  _text_37:any;
  _el_38:any;
  _Icon_38_3:import17.Icon;
  _text_39:any;
  _el_40:any;
  _Label_40_3:import22.Label;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import2.AppElement;
  _DateTime_43_4:import23.DateTime;
  _NG_VALUE_ACCESSOR_43_5:any[];
  _NgModel_43_6:import24.NgModel;
  _NgControl_43_7:any;
  _NgControlStatus_43_8:import25.NgControlStatus;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import2.AppElement;
  _Item_46_4:import21.Item;
  _ItemContent_46_5:import21.ItemContent;
  _query_Label_46_0:import16.QueryList<any>;
  _query_Button_46_1:import16.QueryList<any>;
  _query_Icon_46_2:import16.QueryList<any>;
  _text_47:any;
  _el_48:any;
  _Icon_48_3:import17.Icon;
  _text_49:any;
  _el_50:any;
  _Label_50_3:import22.Label;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  /*private*/ _appEl_53:import2.AppElement;
  _Select_53_4:import26.Select;
  __NG_VALUE_ACCESSOR_53_5:any[];
  _query_Option_53_0:import16.QueryList<any>;
  _text_54:any;
  _el_55:any;
  _Option_55_3:import27.Option;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _Option_58_3:import27.Option;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _Option_61_3:import27.Option;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _Option_64_3:import27.Option;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AboutPage0,renderType_AboutPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_53_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_53_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_53_5 = [this._Select_53_4]); }
    return this.__NG_VALUE_ACCESSOR_53_5;
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Header(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import31.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import12.Navbar(this.parentInjector.get(import32.App),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import33.NavController,(null as any)),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import34.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import13.Button('','',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import14.MenuToggle(this.parentInjector.get(import35.MenuController),new import29.ElementRef(this._el_4),this.parentInjector.get(import30.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_4_6 = new import15.ToolbarItem(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import16.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import17.Icon(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import2.AppElement(9,2,this,this._el_9);
    var compView_9:any = import36.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import18.ToolbarTitle(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'About',(null as any));
    compView_9.create(this._ToolbarTitle_9_4,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_12,'end','');
    this._ToolbarItem_12_3 = new import15.ToolbarItem(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_12_0 = new import16.QueryList<any>();
    this._text_13 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'button',(null as any));
    this.renderer.setElementAttribute(this._el_14,'icon-only','');
    this.renderer.setElementAttribute(this._el_14,'ion-button','');
    this._appEl_14 = new import2.AppElement(14,12,this,this._el_14);
    var compView_14:any = import34.viewFactory_Button0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Button_14_4 = new import13.Button((null as any),'',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_14),this.renderer);
    this._appEl_14.initComponent(this._Button_14_4,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_16,'name','more');
    this.renderer.setElementAttribute(this._el_16,'role','img');
    this._Icon_16_3 = new import17.Icon(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_14.create(this._Button_14_4,[([] as any[]).concat([
        this._text_15,
        this._el_16,
        this._text_17
      ]
    )],(null as any));
    this._text_18 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]).concat([this._el_12]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11,
        this._text_19
      ]
      )
    ]
    ,(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_21 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_22 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_22 = new import2.AppElement(22,(null as any),this,this._el_22);
    var compView_22:any = import37.viewFactory_Content0(this.viewUtils,this.injector(22),this._appEl_22);
    this._Content_22_4 = new import19.Content(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_22),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import38.Keyboard),this.parentInjector.get(import39.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import40.Tabs,(null as any)));
    this._appEl_22.initComponent(this._Content_22_4,([] as any[]),compView_22);
    this._text_23 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','about-header');
    this._text_25 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'img',(null as any));
    this.renderer.setElementAttribute(this._el_26,'src','assets/img/ionic-logo-white.svg');
    this._text_27 = this.renderer.createText(this._el_24,'\n  ',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','about-info');
    this.renderer.setElementAttribute(this._el_29,'padding','');
    this._text_30 = this.renderer.createText(this._el_29,'\n    ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'h4',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Ionic Conference',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n\n    ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_29,'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_34,'no-lines','');
    this._List_34_3 = new import20.List(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_34),this.renderer,this.parentInjector.get(import41.GestureController));
    this._text_35 = this.renderer.createText(this._el_34,'\n      ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','item item-block');
    this._appEl_36 = new import2.AppElement(36,34,this,this._el_36);
    var compView_36:any = import42.viewFactory_Item0(this.viewUtils,this.injector(36),this._appEl_36);
    this._Item_36_4 = new import21.Item(this.parentInjector.get(import43.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_36),this.renderer);
    this._ItemContent_36_5 = new import21.ItemContent();
    this._query_Label_36_0 = new import16.QueryList<any>();
    this._query_Button_36_1 = new import16.QueryList<any>();
    this._query_Icon_36_2 = new import16.QueryList<any>();
    this._appEl_36.initComponent(this._Item_36_4,([] as any[]),compView_36);
    this._text_37 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_38,'item-left','');
    this.renderer.setElementAttribute(this._el_38,'name','calendar');
    this.renderer.setElementAttribute(this._el_38,'role','img');
    this._Icon_38_3 = new import17.Icon(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_38),this.renderer);
    this._text_39 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_40_3 = new import22.Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_40),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'Date',(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'ion-datetime',(null as any));
    this.renderer.setElementAttribute(this._el_43,'displayFormat','MMM DD, YYYY');
    this._appEl_43 = new import2.AppElement(43,36,this,this._el_43);
    var compView_43:any = import44.viewFactory_DateTime0(this.viewUtils,this.injector(43),this._appEl_43);
    this._DateTime_43_4 = new import23.DateTime(this.parentInjector.get(import43.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_43),this.renderer,this._Item_36_4,this.parentInjector.get(import45.PickerController,(null as any)));
    this._NG_VALUE_ACCESSOR_43_5 = [this._DateTime_43_4];
    this._NgModel_43_6 = new import24.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_43_5);
    this._NgControl_43_7 = this._NgModel_43_6;
    this._NgControlStatus_43_8 = new import25.NgControlStatus(this._NgControl_43_7);
    this._appEl_43.initComponent(this._DateTime_43_4,([] as any[]),compView_43);
    compView_43.create(this._DateTime_43_4,([] as any[]),(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_36_0.reset([this._Label_40_3]);
    this._Item_36_4.contentLabel = this._query_Label_36_0.first;
    compView_36.create(this._Item_36_4,[
      ([] as any[]).concat([this._el_38]),
      ([] as any[]).concat([this._el_40]),
      ([] as any[]).concat([
        this._text_37,
        this._text_39,
        this._text_42,
        this._text_44
      ]
      ),
      ([] as any[]).concat([this._el_43]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_45 = this.renderer.createText(this._el_34,'\n\n      ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_34,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','item item-block');
    this._appEl_46 = new import2.AppElement(46,34,this,this._el_46);
    var compView_46:any = import42.viewFactory_Item0(this.viewUtils,this.injector(46),this._appEl_46);
    this._Item_46_4 = new import21.Item(this.parentInjector.get(import43.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_46),this.renderer);
    this._ItemContent_46_5 = new import21.ItemContent();
    this._query_Label_46_0 = new import16.QueryList<any>();
    this._query_Button_46_1 = new import16.QueryList<any>();
    this._query_Icon_46_2 = new import16.QueryList<any>();
    this._appEl_46.initComponent(this._Item_46_4,([] as any[]),compView_46);
    this._text_47 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_48 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_48,'item-left','');
    this.renderer.setElementAttribute(this._el_48,'name','pin');
    this.renderer.setElementAttribute(this._el_48,'role','img');
    this._Icon_48_3 = new import17.Icon(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_48),this.renderer);
    this._text_49 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_50 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_50_3 = new import22.Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_50),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'Location',(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_53 = this.renderer.createElement((null as any),'ion-select',(null as any));
    this._appEl_53 = new import2.AppElement(53,46,this,this._el_53);
    var compView_53:any = import46.viewFactory_Select0(this.viewUtils,this.injector(53),this._appEl_53);
    this._Select_53_4 = new import26.Select(this.parentInjector.get(import32.App),this.parentInjector.get(import43.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_53),this.renderer,this._Item_46_4,this.parentInjector.get(import33.NavController,(null as any)));
    this._query_Option_53_0 = new import16.QueryList<any>();
    this._appEl_53.initComponent(this._Select_53_4,([] as any[]),compView_53);
    this._text_54 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_55 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_55,'selected','');
    this.renderer.setElementAttribute(this._el_55,'value','madison');
    this._Option_55_3 = new import27.Option(new import29.ElementRef(this._el_55));
    this._text_56 = this.renderer.createText(this._el_55,'Madison, WI',(null as any));
    this._text_57 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_58 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_58,'value','austin');
    this._Option_58_3 = new import27.Option(new import29.ElementRef(this._el_58));
    this._text_59 = this.renderer.createText(this._el_58,'Austin, TX',(null as any));
    this._text_60 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_61 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_61,'value','chicago');
    this._Option_61_3 = new import27.Option(new import29.ElementRef(this._el_61));
    this._text_62 = this.renderer.createText(this._el_61,'Chicago, IL',(null as any));
    this._text_63 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_64 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_64,'value','seattle');
    this._Option_64_3 = new import27.Option(new import29.ElementRef(this._el_64));
    this._text_65 = this.renderer.createText(this._el_64,'Seattle, WA',(null as any));
    this._text_66 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_53.create(this._Select_53_4,([] as any[]),(null as any));
    this._text_67 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_46_0.reset([this._Label_50_3]);
    this._Item_46_4.contentLabel = this._query_Label_46_0.first;
    compView_46.create(this._Item_46_4,[
      ([] as any[]).concat([this._el_48]),
      ([] as any[]).concat([this._el_50]),
      ([] as any[]).concat([
        this._text_47,
        this._text_49,
        this._text_52,
        this._text_67
      ]
      ),
      ([] as any[]).concat([this._el_53]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_68 = this.renderer.createText(this._el_34,'\n    ',(null as any));
    this._text_69 = this.renderer.createText(this._el_29,'\n\n    ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_29,'p',(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'\n      The Ionic Conference is a one-day conference featuring talks from the\n      Ionic team. It is focused on Ionic applications being built with\n      Ionic 2. This includes migrating apps from Ionic 1 to Ionic 2,\n      Angular concepts, Webpack, Sass, and many other technologies used\n      in Ionic 2. Tickets are completely sold out, and we’re expecting\n      more than 1000 developers – making this the largest Ionic\n      conference ever!\n    ',(null as any));
    this._text_72 = this.renderer.createText(this._el_29,'\n  ',(null as any));
    this._text_73 = this.renderer.createText((null as any),'\n',(null as any));
    compView_22.create(this._Content_22_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_23,
        this._el_24,
        this._text_28,
        this._el_29,
        this._text_73
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_74 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_43,'ngModelChange',this.eventHandler(this._handle_ngModelChange_43_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_43,'click',this.eventHandler(this._handle_click_43_1.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_43,'keyup.space',this.eventHandler(this._handle_keyup_space_43_2.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_43_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_43_0.bind(this)));
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_53,'click',this.eventHandler(this._handle_click_53_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_53,'keyup.space',this.eventHandler(this._handle_keyup_space_53_1.bind(this)));
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._text_74
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import13.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4; }
    if (((token === import14.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5; }
    if (((token === import15.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6; }
    if (((token === import18.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4; }
    if (((token === import17.Icon) && (16 === requestNodeIndex))) { return this._Icon_16_3; }
    if (((token === import13.Button) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Button_14_4; }
    if (((token === import15.ToolbarItem) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._ToolbarItem_12_3; }
    if (((token === import12.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Navbar_2_4; }
    if (((token === import11.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Header_0_3; }
    if (((token === import17.Icon) && (38 === requestNodeIndex))) { return this._Icon_38_3; }
    if (((token === import22.Label) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Label_40_3; }
    if (((token === import23.DateTime) && (43 === requestNodeIndex))) { return this._DateTime_43_4; }
    if (((token === import47.NG_VALUE_ACCESSOR) && (43 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_43_5; }
    if (((token === import24.NgModel) && (43 === requestNodeIndex))) { return this._NgModel_43_6; }
    if (((token === import48.NgControl) && (43 === requestNodeIndex))) { return this._NgControl_43_7; }
    if (((token === import25.NgControlStatus) && (43 === requestNodeIndex))) { return this._NgControlStatus_43_8; }
    if (((token === import21.Item) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Item_36_4; }
    if (((token === import21.ItemContent) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._ItemContent_36_5; }
    if (((token === import17.Icon) && (48 === requestNodeIndex))) { return this._Icon_48_3; }
    if (((token === import22.Label) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Label_50_3; }
    if (((token === import27.Option) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Option_55_3; }
    if (((token === import27.Option) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._Option_58_3; }
    if (((token === import27.Option) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 62)))) { return this._Option_61_3; }
    if (((token === import27.Option) && ((64 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Option_64_3; }
    if (((token === import26.Select) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._Select_53_4; }
    if (((token === import47.NG_VALUE_ACCESSOR) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._NG_VALUE_ACCESSOR_53_5; }
    if (((token === import21.Item) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._Item_46_4; }
    if (((token === import21.ItemContent) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._ItemContent_46_5; }
    if (((token === import20.List) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._List_34_3; }
    if (((token === import19.Content) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._Content_22_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_4_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_6_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = 'more';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._Icon_16_3.name = currVal_8;
      this._expr_8 = currVal_8;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_22_4.ngOnInit(); }
    const currVal_11:any = 'calendar';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Icon_38_3.name = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_16:any = 'MMM DD, YYYY';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._DateTime_43_4.displayFormat = currVal_16;
      this._expr_16 = currVal_16;
    }
    changes = (null as any);
    const currVal_18:any = this.context.conferenceDate;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._NgModel_43_6.model = currVal_18;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_18,currVal_18);
      this._expr_18 = currVal_18;
    }
    if ((changes !== (null as any))) { this._NgModel_43_6.ngOnChanges(changes); }
    const currVal_25:any = 'pin';
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._Icon_48_3.name = currVal_25;
      this._expr_25 = currVal_25;
    }
    const currVal_30:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this._Option_55_3.selected = currVal_30;
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = 'madison';
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this._Option_55_3.value = currVal_31;
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = 'austin';
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this._Option_58_3.value = currVal_32;
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = 'chicago';
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this._Option_61_3.value = currVal_33;
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = 'seattle';
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._Option_64_3.value = currVal_34;
      this._expr_34 = currVal_34;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4]);
        this._ToolbarItem_4_6._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_12_0.dirty) {
        this._query_Button_12_0.reset([this._Button_14_4]);
        this._ToolbarItem_12_3._buttons = this._query_Button_12_0;
        this._query_Button_12_0.notifyOnChanges();
      }
      if (this._query_Button_36_1.dirty) {
        this._query_Button_36_1.reset(([] as any[]));
        this._Item_36_4._buttons = this._query_Button_36_1;
        this._query_Button_36_1.notifyOnChanges();
      }
      if (this._query_Icon_36_2.dirty) {
        this._query_Icon_36_2.reset([this._Icon_38_3]);
        this._Item_36_4._icons = this._query_Icon_36_2;
        this._query_Icon_36_2.notifyOnChanges();
      }
      if (this._query_Option_53_0.dirty) {
        this._query_Option_53_0.reset([
          this._Option_55_3,
          this._Option_58_3,
          this._Option_61_3,
          this._Option_64_3
        ]
        );
        this._Select_53_4.options = this._query_Option_53_0;
        this._query_Option_53_0.notifyOnChanges();
      }
      if (this._query_Button_46_1.dirty) {
        this._query_Button_46_1.reset(([] as any[]));
        this._Item_46_4._buttons = this._query_Button_46_1;
        this._query_Button_46_1.notifyOnChanges();
      }
      if (this._query_Icon_46_2.dirty) {
        this._query_Icon_46_2.reset([this._Icon_48_3]);
        this._Item_46_4._icons = this._query_Icon_46_2;
        this._query_Icon_46_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_14_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._DateTime_43_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_36_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Select_53_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_46_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = this._Icon_16_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_16,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._Content_22_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_22,'statusbar-padding',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_12:any = this._Icon_38_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_38,'hide',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_17:any = this._DateTime_43_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_43,'datetime-disabled',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_19:any = this._NgControlStatus_43_8.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_43,'ng-untouched',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_43_8.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_43,'ng-touched',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_43_8.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_43,'ng-pristine',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_43_8.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_43,'ng-dirty',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_43_8.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_43,'ng-valid',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_43_8.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_43,'ng-invalid',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_26:any = this._Icon_48_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_48,'hide',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_29:any = this._Select_53_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_53,'select-disabled',currVal_29);
      this._expr_29 = currVal_29;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._Icon_16_3.ngOnDestroy();
    this._Icon_38_3.ngOnDestroy();
    this._DateTime_43_4.ngOnDestroy();
    this._NgModel_43_6.ngOnDestroy();
    this._Icon_48_3.ngOnDestroy();
    this._Select_53_4.ngOnDestroy();
    this._Content_22_4.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.presentPopover($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.conferenceDate = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_43_1($event:any):boolean {
    this._appEl_43.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_43_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_43_2($event:any):boolean {
    this._appEl_43.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_43_4._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_53_0($event:any):boolean {
    this._appEl_53.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_53_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_53_1($event:any):boolean {
    this._appEl_53.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_53_4._keyup()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AboutPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AboutPage> {
  if ((renderType_AboutPage === (null as any))) { (renderType_AboutPage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_AboutPage,{})); }
  return new _View_AboutPage0(viewUtils,parentInjector,declarationEl);
}